FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/web/package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY apps/web .

EXPOSE 3000

CMD ["npm", "run", "dev"]
